name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build bundle app with PyInstaller and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Binary using PyInstaller ManyLinux 2.28 Docker Action
      uses: ./
      with:
        pyinstaller-params: "['-c', '-F', '--name=app', 'tests/app.py']"
    - name: Upload Binary Distribution to Release
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./dist/app
        if-no-files-found: error
    - name: Run app binary and check output
      run: |
        chmod +x ./dist/app
        [[ $(./dist/app) == "Hello out there 👋" ]]
